services:
  frontend:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: wetube-frontend-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    networks:
      - web-network

networks:
  web-network:
    external: true