import Providers from "@/providers";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";
import "./globals.css";
import { AuthProvider } from "@/contexts/auth-context";
import { LoadingBarProvider } from "@/contexts/loading-bar-context";
import { LoadingBar } from "@/components/LoadingBar";
import { NavigationEvents } from "@/components/NavigationEvents";
import {Bounce, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="mdl-js"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoadingBarProvider>
          <AuthProvider>
            <Providers>
              <LoadingBar />
              <NavigationEvents />
              {children}
              <ToastContainer
                  position="top-center"
                  autoClose={3000}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick={false}
                  rtl={false}
                  pauseOnFocusLoss={false}
                  draggable={false}
                  pauseOnHover={false}
                  theme="colored"
                  transition={Bounce}
            />
              
            </Providers>
          </AuthProvider>
        </LoadingBarProvider>
      </body>
    </html>
  );
}
