export const pageUrls = {
    HOME: "/",
    SUBSCRIPTIONS: "/feed/subscribed",
    TRENDING: "/feed/trending",
    HISTORY: "/playlists/history",
    LIKED_VIDEOS: "/playlists/liked",
    ALL_PLAYLISTS: "/playlists/allplaylists",
    STUDIO: "/studio",
    PREMIUM:"/otherservices/premium",
    // MUSIC:"/otherservices/musicwetube",
    SHORTS:"/shorts",
    YOURVIDEO:"/studio",
    SEELATER:"/playlists/seelater",
    ROOMS:"/rooms",
    LIVESTREAM:"/livestream",
    YOURVIDEO:"/your-video",
    SEELATER:"/see-later",
    MUSIC: "/music",
    SPORTS: "/sports",
    REPORT: "/otherservices/reportdiary",
    SUPPORT:"/otherservices/support",
    FEEDBACK: "/otherservices/feedback"
} as const;