// data/channels.ts
export const channels = [
  {
    id: 1,
    name: "Tech World",
    icon: "https://yt3.ggpht.com/GFq21KMUbKV6pLEFpZs8tWIFwQzxQo_2Y1zKk7RL6jCrt02hCAwgM74onPmqmLq6TK6JvnUzZW4=s68-c-k-c0x00ffffff-no-rj",
    subscribers: "1.2M",
    description: "Technology tutorials and gadget reviews.",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 2,
    name: "Foodie Fun",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 3,
    name: "new",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 4,
    name: "Khai",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 5,
    name: "NTN",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 6,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 7,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 8,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 9,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 10,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 11,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 12,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 13,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 14,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 15,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 16,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 17,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 18,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 19,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
  {
    id: 20,
    name: "Coding",
    icon: "https://placehold.co/100x100?text=FF",
    subscribers: "800K",
    description: "Delicious recipes and food challenges!",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
  },
];
